# Class definition for pipeline endpoint object
# Data objects can be instantiated as:
#
# Object.Base.dai_endpoint.1 {
#	type	"HDA"
#	dai_index	5
#	direction	"playback"
# }
#
Class.Base."pipe_endpoint" {

	# pipeline ID
	DefineAttribute."dai_index" {}

	DefineAttribute."direction" {}

	DefineAttribute."type" {
		constraints {
			!valid_values [
				"SSP"
				"DMIC"
				"HDA"
				"ALH"
			]
		}
	}

	attributes {
		!constructor [
			"type"
			"dai_index"
			"direction"
		]
		#
		# pipeline endpoint objects instantiated within the same alsaconf node must have
		# unique direction attribute
		#
		unique	"direction"
	}
}
