# Class definition for pipeline endpoint object
# Data objects can be instantiated as:
#
# Object.Base.endpoint.1 {
#	type	"dai"
#	index	5
#	direction	"playback"
# }
#
Class.Base."pipe_endpoint" {

	DefineAttribute."instance" {}

	# pipeline ID
	DefineAttribute."index" {}

	DefineAttribute."direction" {}

	attributes {
		!constructor [
			"direction"
			"index"
			"instance"
		]
		#
		# pipeline endpoint objects instantiated within the same alsaconf node must have
		# unique instance attribute
		#
		unique	"instance"
	}
}
