#
# Just a Backend DAI
#
# All attributes defined herein are namespaced by alsatplg to
# "Object.Pipeline.io-gateway.N.attribute_name"
#
# Usage: io-gateway pipeline object can be instantiated as:
#
# Object.Pipeline.io-gateway."N" {
#	direction	"playback"
	dynamic_pipeline 1
# }
#
# Where N is the unique pipeline ID within the same alsaconf node.
#

<include/common/input_audio_format.conf>
<include/common/output_audio_format.conf>
<include/components/dai-copier.conf>
<include/components/pipeline.conf>

Class.Pipeline."pipeline" {

	<include/pipelines/pipeline-common.conf>

	attributes {
		!constructor [
			"index"
		]

		#
		# pipeline objects instantiated within the same alsaconf node must have
		# unique instance attribute
		#
		unique	"instance"
	}

	dynamic_pipeline 1
}
