#
# BE playback pipeline: mixout-gain-efx-mbdrc-dai-copier.
#
# All attributes defined herein are namespaced
# by alsatplg to "Object.Pipeline.mixout-gain-efx-mbdrc-dai-copier-playback.N.attribute_name"
#
# Usage: mixout-gain-efx-mbdrc-dai-copier-playback pipeline object can be instantiated as:
#
# Object.Pipeline.mixout-gain-efx-mbdrc-dai-copier-playback."N" {
# 	period		1000
# 	time_domain	"timer"
# }
#
# Where N is the unique pipeline ID within the same alsaconf node.
#

<include/common/input_audio_format.conf>
<include/common/output_audio_format.conf>
<include/components/dai-copier.conf>
<include/components/gain.conf>
<include/components/mixout.conf>
<include/components/pipeline.conf>
<include/controls/bytes.conf>
<include/components/eqiir.conf>
<include/components/eqfir.conf>
<include/components/multiband_drc.conf>
<platform/intel/efx-default.conf>

Class.Pipeline."mixout-gain-efx-mbdrc-dai-copier-playback" {
	<include/pipelines/cavs/mixout-gain-dai-copier-playback-base.conf>
	<include/pipelines/cavs/eqiir-eqfir.conf>

	Object.Widget {
		multiband_drc."1" {
			num_input_audio_formats 1
			num_output_audio_formats 1

			Object.Base.input_audio_format [
				{
					in_bit_depth		32
					in_valid_bit_depth	32
				}
			]
			Object.Base.output_audio_format [
				{
					out_bit_depth		32
					out_valid_bit_depth	32
				}
			]

			Object.Control.bytes."1" {
				IncludeByKey.EFX_MBDRC_PARAMS {
					"passthrough"	"include/components/multiband_drc/passthrough.conf"
					"default"	"include/components/multiband_drc/default.conf"
				}
			}
		}
	}

	Object.Base {
		route.4 {
			source eqfir.$index.1
			sink	multiband_drc.$index.1
		}
	}
}
